server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanjayvingole/olx-project
          username: sanjayvingole
          clone-on-start: true
